spring:
  datasource:
    url: jdbc:mysql://localhost:3306/esercitazione
    username: root
    password: gTYù=(iA5?&_/
    driver-class-name: com.mysql.cj.jdbc.Driver
jpa:
  database: mysql
  show-sql: true
  hibernate:
    ddl-auto: create-drop
