spring:
  datasource:
    url: jdbc:mysql://localhost:3306/prova
    username: root
    password: gTYù=(iA5?&_/

  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: create-drop
